### ISSUE TITLE
centos make error

### ISSUE THREAD

**Issue by rawmaterials** [dcousens/fast-dat-parser#12] opened 2018-01-04 09:14 UTC
```
[root@localhost fast-dat-parser]# make
g++ -pedantic -std=c++1z -W -Wall -Wcast-qual -Wconversion -Werror -Wextra -Wwrite-strings -O3 -Iinclude -MMD -MP -c src/bestchain.cpp -o src/bestchain.o
g++: error: unrecognized command line option ‘-std=c++1z’
make: *** [src/bestchain.o] Error 1
```

```
[root@localhost fast-dat-parser]# g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC)

```

do i need newer version of gcc ? 

`running centos 7 x64 3.10.0-693.11.1.el7.x86_64
`

**Comment by rawmaterials** [comment] 2018-01-04 09:32
okie., updated my gcc

[root@localhost fast-dat-parser]# g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-4/root/usr/libexec/gcc/x86_64-redhat-linux/5.3.1/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-4/root/usr --mandir=/opt/rh/devtoolset-4/root/usr/share/man --infodir=/opt/rh/devtoolset-4/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --enable-plugin --with-linker-hash-style=gnu --enable-initfini-array --disable-libgcj --with-default-libstdcxx-abi=gcc4-compatible --with-isl=/builddir/build/BUILD/gcc-5.3.1-20160406/obj-x86_64-redhat-linux/isl-install --enable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 5.3.1 20160406 (Red Hat 5.3.1-6) (GCC)


now i get these errors.,

[root@localhost fast-dat-parser]# make
g++ -pedantic -std=c++1z -W -Wall -Wcast-qual -Wconversion -Werror -Wextra -Wwrite-strings -O3 -Iinclude -MMD -MP -c src/bestchain.cpp -o src/bestchain.o
In file included from src/bestchain.cpp:10:0:
include/serial.hpp: In function ‘auto serial::peek(const R&)’:
include/serial.hpp:17:48: error: expected ‘,’ before ‘)’ token
   static_assert(std::is_same<T, uint8_t>::value);
                                                ^
include/serial.hpp:17:48: error: expected string-literal before ‘)’ token
include/serial.hpp:18:43: error: expected ‘,’ before ‘)’ token
   static_assert(sizeof(E) % sizeof(T) == 0);
                                           ^
include/serial.hpp:18:43: error: expected string-literal before ‘)’ token
include/serial.hpp: In function ‘void serial::place(R&, E)’:
include/serial.hpp:40:48: error: expected ‘,’ before ‘)’ token
   static_assert(std::is_same<T, uint8_t>::value);
                                                ^
include/serial.hpp:40:48: error: expected string-literal before ‘)’ token
include/serial.hpp:41:43: error: expected ‘,’ before ‘)’ token
   static_assert(sizeof(E) % sizeof(T) == 0);
                                           ^
include/serial.hpp:41:43: error: expected string-literal before ‘)’ token
make: *** [src/bestchain.o] Error 1

**Comment by dcousens** [comment] 2018-01-05 01:24
@rawmaterials this is technically a duplicate of https://github.com/dcousens/fast-dat-parser/issues/11.

The repository uses `C++17`,  but maybe if wanted I'll make a PR to revert it C++14 or something...

**Closed** 2018-01-05 01:24 UTC
Labels: question

**Comment by rawmaterials** [comment] 2018-01-05 02:52
i added optional message and its working now., thanks.

**Comment by scriptzteam** [comment] 2018-05-21 15:16
@rawmaterials what you added and where pls :D

**Comment by rawmaterials** [comment] 2018-05-21 16:43
@scriptzteam here is my serial.hpp


`// TODO: probaby unrelated to ranges, but
#pragma once

#include <algorithm>
#include "ranger.hpp"

#include "endian.h"
#if __BYTE_ORDER != __LITTLE_ENDIAN
#error "big endian architecture not supported"
#endif

namespace serial {
	template <typename E, bool BE = false, typename R>
	auto peek (const R& r) {
		using T = typename R::value_type;

		static_assert(std::is_same<T, uint8_t>::value, "this is custom message");
		static_assert(sizeof(E) % sizeof(T) == 0, "this is custom message");

		constexpr auto count = sizeof(E) / sizeof(T);
		assert(count <= r.size());

		E value;
		auto copy = range(r);
		auto ptr = reinterpret_cast<T*>(&value);

		if (BE) {
			for (size_t i = 0; i < count; ++i, copy.popFront()) ptr[count - 1 - i] = copy.front();
		} else {
			for (size_t i = 0; i < count; ++i, copy.popFront()) ptr[i] = copy.front();
		}

		return value;
	}

	template <typename E, bool BE = false, typename R>
	void place (R& r, const E e) {
		using T = typename R::value_type;

		static_assert(std::is_same<T, uint8_t>::value, "this is custom message");
		static_assert(sizeof(E) % sizeof(T) == 0, "this is custom message");

		constexpr auto count = sizeof(E) / sizeof(T);
		assert(count <= r.size());

		auto copy = range(r);
		auto ptr = reinterpret_cast<const T*>(&e);

		if (BE) {
			for (size_t i = 0; i < count; ++i, copy.popFront()) copy.front() = ptr[count - 1 - i];
		} else {
			for (size_t i = 0; i < count; ++i, copy.popFront()) copy.front() = ptr[i];
		}
	}

	template <typename E, bool BE = false, typename R>
	auto read (R& r) {
		using T = typename R::value_type;

		const auto e = peek<E, BE, R>(r);
		r.popFrontN(sizeof(E) / sizeof(T));
		return e;
	}

	template <typename E, bool BE = false, typename R>
	void put (R& r, const E e) {
		using T = typename R::value_type;

		place<E, BE, R>(r, e);
		r.popFrontN(sizeof(E) / sizeof(T));
	}

	// rvalue references wrappers
	template <typename E, bool BE = false, typename R> void place (R&& r, const E e) { place<E, BE, R>(r, e); }
	template <typename E, bool BE = false, typename R> auto read (R&& r) { return read<E, BE, R>(r); }
	template <typename E, bool BE = false, typename R> void put (R&& r, const E e) { put<E, BE, R>(r, e); }
}
`

**Comment by dcousens** [comment] 2018-05-22 01:51
@scriptzteam @rawmaterials I fixed the issue.

https://github.com/bitcoinjs/fast-dat-parser/commit/793c5d8a9557f492c4eeb6eddfc85a6c9ffec088

**Comment by dcousens** [comment] 2018-06-09 08:34
@scriptzteam compiling on a 32-bit system?

**Comment by dcousens** [comment] 2018-06-09 08:36
@scriptzteam probably need to lower the number of warnings,  as `-Werror=unused-function` is unnecessarily stopping you.
